
import Header from "@/components/common/Header";
import "./globals.css";
import Navbar from "@/components/common/Navbar";

export const metadata = {
  title: "SailIt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
